# Generated by Django 2.1.2 on 2019-01-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagory', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'classification',
            },
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=250)),
                ('area', models.CharField(max_length=50)),
                ('othername', models.CharField(default='', max_length=20)),
                ('image', models.ImageField(default='demand/init.png', upload_to='demand/')),
                ('starttime', models.DateTimeField(auto_now=True)),
                ('endtime', models.DateField()),
                ('money', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wechar', models.CharField(default='', max_length=20)),
                ('QQ', models.CharField(default='', max_length=20, null=True)),
                ('tel', models.CharField(default='', max_length=11, null=True)),
                ('count', models.IntegerField(default=0)),
                ('iscomplete', models.BooleanField(default=False)),
                ('msglevel', models.BooleanField(default=False)),
                ('catagoryid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='commend.Classification')),
                ('uerid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Userinfo')),
            ],
            options={
                'db_table': 'demand',
            },
        ),
    ]
