# Generated by Django 2.1.2 on 2019-01-05 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prosfession', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=20)),
                ('office', models.CharField(max_length=20)),
                ('truename', models.CharField(max_length=20, null=True)),
                ('companyintroducion', models.TextField(null=True)),
                ('jobs', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Job')),
            ],
            options={
                'db_table': 'professional',
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=64)),
                ('nickname', models.CharField(default='', max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=11)),
                ('vip', models.IntegerField(default=0)),
                ('wechar', models.CharField(default='', max_length=20, null=True)),
                ('QQ', models.CharField(default='', max_length=20, null=True)),
                ('email', models.EmailField(default='', max_length=254, null=True)),
                ('bankcard', models.CharField(default='', max_length=20, null=True)),
                ('headimg', models.ImageField(default='user/tx00.png', upload_to='user/')),
                ('requirement_count', models.IntegerField(default=0)),
                ('createtime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'userinfo',
            },
        ),
        migrations.AddField(
            model_name='professional',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.Userinfo'),
        ),
    ]
